### ISSUE TITLE
not working on Craft CMS 3.0.0-RC10.1

### ISSUE THREAD

**Issue by romanov-sky** [mikestecker/craft3-videoembedder#4]
Can you check, please.. this plugin doesn't work at all with Craft CMS 3.0.0-RC10.1

**Comment by mikestecker** [comment]
@romanov-sky Can you share the error that you are receiving? I believe I know what might be wrong because I found a mistake in my documentation so hopefully this resolves it.

Prior documentation used `{{ craft.videoEmbed.getEmbedUrl('https://www.youtube.com/watch?v=6xWpo5Dn254') }}` and it should be `{{ craft.videoEmbedder.getEmbedUrl('https://www.youtube.com/watch?v=6xWpo5Dn254') }}`

So essentially just change references from `videoEmbed` to `videoEmbedder`. Apologies for that! Let me know if that resolves it for you.

**Comment by romanov-sky** [comment]
Thank you, it works now! One small thing though, it generates the links with double slash '//' before the actual link. Can you check it?

**Comment by mikestecker** [comment]
The use of the double slash was purposeful to prevent mixing http and https and throwing errors for your users. This is a good explanation of why you would want to do this: https://stackoverflow.com/a/9646435/1133675
